language: python
python: 
  - 3.6.3
install:
  - pip install -r requirements.txt
script:
  - python manage.py test finance.unit_tests
  - python manage.py test finance.functional_tests
addons:
  chrome: stable
