language: python
python: 
  - 3.6.3
install:
  - pip install -r requirements.txt
before_script:
  - echo $PATH
  - wget http://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
script:
  - python manage.py test finance.unit_tests
  - python manage.py test finance.functional_tests
addons:
  chrome: stable
