version: '3'

services:
  db:
    image: 'postgresql'
  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/usr/src/app
    depends_on: 
      - db

  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on: 
      - db
      - migration